import type { Metadata } from "next";
import { routing } from "@/i18n/routing";

/**
 * Build the absolute site origin from env. SITE_URL takes precedence;
 * fall back to NEXT_PUBLIC_SITE_URL, then localhost for dev.
 */
export function siteOrigin(): string {
  return (
    process.env.SITE_URL ??
    process.env.NEXT_PUBLIC_SITE_URL ??
    "http://localhost:3000"
  );
}

export function absoluteUrl(path: string): string {
  const origin = siteOrigin().replace(/\/$/, "");
  return `${origin}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Build the `alternates` object for a localized route given the path
 * template and a slugs-per-locale map. Used by both modules and articles.
 *
 * Example:
 *   buildAlternates({
 *     rendered: 'vi',
 *     canonicalPath: '/vi/academy/order-flow-footprints/delta-la-gi',
 *     alternates: { en: '/en/academy/order-flow-footprints/delta-explained',
 *                   vi: '/vi/academy/order-flow-footprints/delta-la-gi' },
 *   })
 */
export function buildAlternates({
  canonicalPath,
  alternates,
}: {
  canonicalPath: string;
  alternates: Record<string, string>;
}): NonNullable<Metadata["alternates"]> {
  return {
    canonical: absoluteUrl(canonicalPath),
    languages: Object.fromEntries(
      Object.entries(alternates).map(([lang, p]) => [
        lang,
        absoluteUrl(p),
      ]),
    ),
  };
}

/**
 * Add an `x-default` hreflang entry to a locale→absolute-URL map.
 *
 * Google recommends an `x-default` pointing at the page served to users
 * whose language matches none of the listed alternates. Guests on this site
 * are forced to `publicLocale`, so that locale's URL is the right default.
 *
 * Picks `languages[publicLocale]` when present, else an explicit
 * `fallbackUrl` (e.g. the page's own canonical), else the first entry. The
 * `x-default` URL is always a duplicate of an existing alternate so it
 * resolves to a real 200 / self-canonical page. No-op on an empty map.
 */
export function withXDefault(
  languages: Record<string, string>,
  publicLocale: string,
  fallbackUrl?: string,
): Record<string, string> {
  const target =
    languages[publicLocale] ?? fallbackUrl ?? Object.values(languages)[0];
  if (!target) return languages;
  return { ...languages, "x-default": target };
}

/**
 * Localized OG image URL — defaults to /opengraph-image generated by
 * a per-route opengraph-image.tsx. Falls back to a configured static
 * if provided.
 */
export function defaultOgImage(): string {
  return absoluteUrl("/opengraph-image");
}

/**
 * Tiny helper that turns a JSON-LD object into the <script> tag content.
 * Server Components render it inline; passes through `cn` if anyone
 * wants to call from a Client Component too.
 */
export function jsonLdScript(data: Record<string, unknown>): string {
  // Escape `</` to avoid breaking out of the <script> tag in HTML.
  return JSON.stringify(data).replace(/</g, "\\u003c");
}

/* ── Stable JSON-LD @ids ───────────────────────────────────────────────
 * The same identifier across every page and locale, so engines merge the
 * Organization / WebSite / Person into one connected entity regardless of
 * how many <script> blocks (or pages) reference it. */
export function organizationId(): string {
  return `${siteOrigin()}/#organization`;
}
export function webSiteId(): string {
  return `${siteOrigin()}/#website`;
}
/** Locale-independent Person id (derived from the author slug). */
export function personEntityId(slug: string): string {
  return `${siteOrigin()}/#person-${slug}`;
}

/**
 * Merge JSON-LD nodes into a single `{ @context, @graph: [...] }` document,
 * stripping each node's own `@context` (the wrapper carries it). Falsy
 * nodes are dropped, so callers can pass `cond && buildX(...)`.
 */
export function buildGraph(
  nodes: Array<Record<string, unknown> | null | undefined>,
): Record<string, unknown> {
  const graph = nodes
    .filter((n): n is Record<string, unknown> => Boolean(n))
    .map((n) => {
      const copy = { ...n };
      delete copy["@context"];
      return copy;
    });
  return { "@context": "https://schema.org", "@graph": graph };
}

/**
 * WebPage node — the per-URL hub linking the page to the WebSite and its
 * BreadcrumbList. `url` is the page canonical (path or absolute).
 */
export function buildWebPageJsonLd(opts: {
  url: string;
  name: string;
  description?: string | null;
  inLanguage: string;
  primaryImageUrl?: string | null;
  hasBreadcrumb?: boolean;
  /** When set, the page is typed CollectionPage with an ItemList mainEntity
   *  of the listed (visible) items — a content-hierarchy map for AI fan-out
   *  (GEO; no rich-result expectation). */
  collection?: Array<{ url: string; name: string }>;
}): Record<string, unknown> {
  const abs = absoluteUrl(opts.url);
  const json: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": opts.collection ? ["CollectionPage", "WebPage"] : "WebPage",
    "@id": `${abs}#webpage`,
    url: abs,
    name: opts.name,
    inLanguage: opts.inLanguage,
    isPartOf: { "@id": webSiteId() },
  };
  if (opts.description) json.description = opts.description;
  if (opts.hasBreadcrumb) json.breadcrumb = { "@id": `${abs}#breadcrumb` };
  if (opts.primaryImageUrl)
    json.primaryImageOfPage = {
      "@type": "ImageObject",
      url: opts.primaryImageUrl,
    };
  if (opts.collection && opts.collection.length > 0) {
    json.mainEntity = {
      "@type": "ItemList",
      itemListElement: opts.collection.map((it, i) => ({
        "@type": "ListItem",
        position: i + 1,
        url: absoluteUrl(it.url),
        name: it.name,
      })),
    };
  }
  return json;
}

/**
 * Build the WebSite JSON-LD that lives in the root layout.
 */
export function buildWebSiteJsonLd(opts: {
  siteName: string;
  description: string;
  supportedLocales: string[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": webSiteId(),
    name: opts.siteName,
    url: siteOrigin(),
    description: opts.description,
    inLanguage: opts.supportedLocales,
    publisher: { "@id": organizationId() },
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteOrigin()}/${routing.defaultLocale}/search?q={query}`,
      "query-input": "required name=query",
    },
  };
}

export function buildOrganizationJsonLd(opts: {
  siteName: string;
  description?: string | null;
  logoUrl?: string | null;
  contactEmail?: string | null;
  twitterHandle?: string | null;
  /** Extra verified profile URLs (LinkedIn / YouTube / Wikidata …). */
  extraSameAs?: string[];
  /** Core topics the brand covers → knowsAbout (topical authority). */
  knowsAbout?: string[];
}) {
  const sameAs: string[] = [];
  if (opts.twitterHandle) {
    const handle = opts.twitterHandle.replace(/^@/, "");
    sameAs.push(`https://x.com/${handle}`);
  }
  for (const u of opts.extraSameAs ?? []) {
    if (u && u.trim()) sameAs.push(u.trim());
  }
  const logo = opts.logoUrl
    ? opts.logoUrl.startsWith("http")
      ? opts.logoUrl
      : absoluteUrl(opts.logoUrl)
    : absoluteUrl("/opengraph-image");
  const json: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": organizationId(),
    name: opts.siteName,
    url: siteOrigin(),
    logo: { "@type": "ImageObject", url: logo },
  };
  if (opts.description) json.description = opts.description;
  if (sameAs.length > 0) json.sameAs = Array.from(new Set(sameAs));
  if (opts.knowsAbout && opts.knowsAbout.length > 0)
    json.knowsAbout = opts.knowsAbout;
  if (opts.contactEmail) {
    json.contactPoint = {
      "@type": "ContactPoint",
      email: opts.contactEmail,
      contactType: "customer support",
    };
  }
  return json;
}

export function buildBreadcrumbJsonLd(
  items: Array<{ name: string; url: string }>,
  opts?: { id?: string },
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    ...(opts?.id ? { "@id": opts.id } : {}),
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.url),
    })),
  };
}

export function buildArticleJsonLd(opts: {
  headline: string;
  description: string | null;
  url: string;
  imageUrl: string;
  datePublished: Date | null;
  dateModified: Date | null;
  /** Real article author — emitted as a Person (E-E-A-T), not the org.
   *  `slug` (when present) yields a stable cross-locale Person @id. */
  author: {
    name: string;
    url?: string | null;
    image?: string | null;
    slug?: string | null;
  };
  inLanguage: string;
  /** Localized tag names → keywords. */
  keywords?: string[];
  /** Module display name → articleSection. */
  articleSection?: string;
  wordCount?: number;
  /** Reading time in minutes → timeRequired (ISO-8601 duration). */
  timeRequiredMinutes?: number;
  /** e.g. "Beginner" / "Intermediate" / "Advanced". */
  educationalLevel?: string;
  /** Pillar module — emitted as `isPartOf` LearningResource. */
  modulePath?: { name: string; url: string };
  /** Primary topics (DefinedTerm nodes) the article is about. */
  about?: Array<Record<string, unknown>>;
  /** Secondary glossary terms mentioned in the body (DefinedTerm nodes). */
  mentions?: Array<Record<string, unknown>>;
}) {
  const author: Record<string, unknown> = {
    "@type": "Person",
    name: opts.author.name,
  };
  if (opts.author.slug) author["@id"] = personEntityId(opts.author.slug);
  if (opts.author.url) author.url = absoluteUrl(opts.author.url);
  if (opts.author.image) author.image = opts.author.image;

  const canonical = absoluteUrl(opts.url);
  return {
    "@context": "https://schema.org",
    // Co-typed: an Article that is also a LearningResource (educational site).
    "@type": ["Article", "LearningResource"],
    "@id": `${canonical}#article`,
    headline: opts.headline,
    description: opts.description ?? undefined,
    image: {
      "@type": "ImageObject",
      url: absoluteUrl(opts.imageUrl),
      width: 1200,
      height: 630,
    },
    mainEntityOfPage: { "@id": `${canonical}#webpage` },
    inLanguage: opts.inLanguage,
    datePublished: opts.datePublished?.toISOString(),
    dateModified: (opts.dateModified ?? opts.datePublished)?.toISOString(),
    author,
    publisher: { "@id": organizationId() },
    isAccessibleForFree: true,
    learningResourceType: "article",
    educationalUse: "self-study",
    educationalLevel: opts.educationalLevel ?? "intermediate",
    keywords:
      opts.keywords && opts.keywords.length > 0 ? opts.keywords : undefined,
    articleSection: opts.articleSection ?? undefined,
    wordCount: opts.wordCount && opts.wordCount > 0 ? opts.wordCount : undefined,
    timeRequired:
      opts.timeRequiredMinutes && opts.timeRequiredMinutes > 0
        ? `PT${opts.timeRequiredMinutes}M`
        : undefined,
    about:
      opts.about && opts.about.length > 0 ? opts.about : undefined,
    mentions:
      opts.mentions && opts.mentions.length > 0 ? opts.mentions : undefined,
    isPartOf: opts.modulePath
      ? {
          "@type": "LearningResource",
          name: opts.modulePath.name,
          url: absoluteUrl(opts.modulePath.url),
          educationalLevel: "intermediate",
        }
      : undefined,
  };
}

/**
 * Person JSON-LD for an author profile page (E-E-A-T). The stable `@id`
 * (`<url>#person`) is reused as the `author` reference from every Article
 * the person wrote, so engines resolve a single connected entity.
 */
export function buildPersonJsonLd(opts: {
  name: string;
  /** Author slug → stable cross-locale `@id` (`#person-<slug>`). */
  slug: string;
  /** Absolute, human-facing author-profile URL. */
  url: string;
  description?: string | null;
  image?: string | null;
  jobTitle?: string | null;
  sameAs?: string[];
  knowsAbout?: string[];
  /** Link the author to the publisher Organization by @id. */
  worksForOrg?: boolean;
}) {
  const json: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": personEntityId(opts.slug),
    name: opts.name,
    url: opts.url,
  };
  if (opts.description) json.description = opts.description;
  if (opts.image) json.image = opts.image;
  if (opts.jobTitle) json.jobTitle = opts.jobTitle;
  if (opts.sameAs && opts.sameAs.length > 0) json.sameAs = opts.sameAs;
  if (opts.knowsAbout && opts.knowsAbout.length > 0)
    json.knowsAbout = opts.knowsAbout;
  if (opts.worksForOrg) json.worksFor = { "@id": organizationId() };
  return json;
}

/**
 * ProfilePage wrapper around a Person (or a Person `@id` reference). Google's
 * ProfilePage type; no visible rich result for a plain author bio but it
 * disambiguates the page's primary entity for both Search and AI.
 */
export function buildProfilePageJsonLd(opts: {
  url: string;
  inLanguage: string;
  person: Record<string, unknown>;
  dateModified?: Date | null;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    "@id": `${opts.url}#profilepage`,
    url: opts.url,
    inLanguage: opts.inLanguage,
    isPartOf: { "@id": webSiteId() },
    dateModified: opts.dateModified?.toISOString(),
    mainEntity: opts.person,
  };
}

export function buildLearningResourceJsonLd(opts: {
  name: string;
  description: string | null;
  url: string;
  inLanguage: string;
  teaches: string[];
}) {
  const abs = absoluteUrl(opts.url);
  return {
    "@context": "https://schema.org",
    "@type": "LearningResource",
    "@id": `${abs}#learningresource`,
    name: opts.name,
    description: opts.description ?? undefined,
    url: abs,
    inLanguage: opts.inLanguage,
    isPartOf: { "@id": webSiteId() },
    provider: { "@id": organizationId() },
    educationalUse: "instruction",
    educationalLevel: "intermediate",
    teaches: opts.teaches,
    learningResourceType: "course module",
  };
}

/** Build FAQPage schema from H2 headings that look like questions. */
export function extractFaqQuestions(bodyMdx: string): Array<{
  question: string;
  answer: string;
}> {
  const lines = bodyMdx.split("\n");
  const faqs: Array<{ question: string; answer: string }> = [];
  let currentQ: string | null = null;
  let currentAnswer: string[] = [];
  let inFence = false;
  for (const line of lines) {
    if (line.trimStart().startsWith("```")) {
      inFence = !inFence;
      if (currentQ) currentAnswer.push(line);
      continue;
    }
    if (inFence) {
      if (currentQ) currentAnswer.push(line);
      continue;
    }
    const m = /^##\s+(.+?)\s*$/.exec(line);
    if (m) {
      if (currentQ) {
        const answer = currentAnswer.join("\n").trim();
        if (answer) faqs.push({ question: currentQ, answer });
      }
      const heading = m[1].trim();
      currentQ = isQuestionLike(heading) ? heading : null;
      currentAnswer = [];
      continue;
    }
    if (currentQ) currentAnswer.push(line);
  }
  if (currentQ) {
    const answer = currentAnswer.join("\n").trim();
    if (answer) faqs.push({ question: currentQ, answer });
  }
  return faqs;
}

function isQuestionLike(heading: string): boolean {
  // Plain question mark, or starts with common interrogative words EN/VI.
  if (heading.endsWith("?")) return true;
  return /^(what|how|why|when|where|which|who|cách|tại sao|là gì|gì\b)/i.test(
    heading,
  );
}

export function buildFaqJsonLd(
  questions: Array<{ question: string; answer: string }>,
) {
  if (questions.length === 0) return null;
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: questions.map((q) => ({
      "@type": "Question",
      name: q.question,
      acceptedAnswer: { "@type": "Answer", text: markdownToPlain(q.answer) },
    })),
  };
}

function markdownToPlain(s: string): string {
  return s
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\s*[#>\-*]\s*/gm, "")
    .replace(/\n{2,}/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 2000);
}
