export const dynamic = "force-static";

const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsl:output method="html" encoding="UTF-8" indent="yes" doctype-system="about:legacy-compat"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap</title>
        <style>
          :root { color-scheme: light dark; }
          * { box-sizing: border-box; }
          body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #1a1a1a;
            background: #f6f7f9;
          }
          .bar {
            background: #0e0d0d;
            color: #fff;
            padding: 28px 24px;
            border-bottom: 3px solid #ff6a00;
          }
          .bar .inner { max-width: 1100px; margin: 0 auto; }
          .bar h1 { margin: 0; font-size: 22px; font-weight: 800; letter-spacing: -0.3px; }
          .bar h1 span { color: #ff6a00; }
          .bar p { margin: 8px 0 0; font-size: 13px; color: #b9b9be; max-width: 720px; line-height: 1.5; }
          .wrap { max-width: 1100px; margin: 0 auto; padding: 24px; }
          .meta {
            display: inline-block;
            font-size: 12px;
            font-weight: 600;
            color: #555;
            background: #fff;
            border: 1px solid #e4e6ea;
            border-radius: 999px;
            padding: 6px 14px;
            margin-bottom: 16px;
          }
          .card {
            background: #fff;
            border: 1px solid #e4e6ea;
            border-radius: 12px;
            overflow: hidden;
          }
          .scroll { overflow-x: auto; }
          table { width: 100%; border-collapse: collapse; font-size: 14px; }
          th, td { text-align: left; padding: 12px 16px; white-space: nowrap; }
          th {
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.6px;
            color: #6b7280;
            background: #fafbfc;
            border-bottom: 1px solid #e4e6ea;
          }
          td { border-bottom: 1px solid #f0f1f3; }
          tr:last-child td { border-bottom: 0; }
          tbody tr:hover { background: #fafbfc; }
          td.url { white-space: normal; word-break: break-all; }
          a { color: #c2410c; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .num { text-align: right; font-variant-numeric: tabular-nums; color: #6b7280; }
          .muted { color: #9aa0a6; }
          footer { max-width: 1100px; margin: 0 auto; padding: 8px 24px 40px; font-size: 12px; color: #9aa0a6; }
          @media (prefers-color-scheme: dark) {
            body { background: #0b0c0e; color: #e6e6e9; }
            .meta { background: #16171a; border-color: #24262b; color: #b9b9be; }
            .card { background: #121316; border-color: #24262b; }
            th { background: #16171a; color: #9aa0a6; border-color: #24262b; }
            td { border-color: #1c1e22; }
            tbody tr:hover { background: #16171a; }
            a { color: #ff8a3d; }
            .num, .muted { color: #8b9096; }
          }
        </style>
      </head>
      <body>
        <div class="bar">
          <div class="inner">
            <h1>XML <span>Sitemap</span></h1>
            <p>This is an XML sitemap, meant for search engines like Google. It lists the pages of this site. Each row links to a page or to another sitemap.</p>
          </div>
        </div>
        <div class="wrap">
          <xsl:apply-templates select="s:sitemapindex"/>
          <xsl:apply-templates select="s:urlset"/>
        </div>
        <footer>Generated by wiki.xapy.io</footer>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="s:sitemapindex">
    <div class="meta"><xsl:value-of select="count(s:sitemap)"/> sitemaps</div>
    <div class="card">
      <div class="scroll">
        <table>
          <thead>
            <tr><th>Sitemap</th><th>Last modified</th></tr>
          </thead>
          <tbody>
            <xsl:for-each select="s:sitemap">
              <tr>
                <td class="url"><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                <td class="muted"><xsl:value-of select="s:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </div>
    </div>
  </xsl:template>

  <xsl:template match="s:urlset">
    <div class="meta"><xsl:value-of select="count(s:url)"/> URLs</div>
    <div class="card">
      <div class="scroll">
        <table>
          <thead>
            <tr>
              <th>URL</th>
              <th>Languages</th>
              <th class="num">Priority</th>
              <th>Change freq.</th>
              <th>Last modified</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="s:url">
              <tr>
                <td class="url"><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                <td class="muted"><xsl:value-of select="count(xhtml:link)"/></td>
                <td class="num"><xsl:value-of select="s:priority"/></td>
                <td class="muted"><xsl:value-of select="s:changefreq"/></td>
                <td class="muted"><xsl:value-of select="s:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </div>
    </div>
  </xsl:template>
</xsl:stylesheet>
`;

export async function GET() {
  return new Response(XSL, {
    headers: {
      "Content-Type": "text/xsl; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
